version: 0-1-0
application: huge-echo
runtime: python27
api_version: 1
threadsafe: true

includes:
- echo/include.yaml

handlers:

## Endpoints handler: Must be /_ah/spi. Apps send requests to /_ah/api, but these are handled at /_ah/spi!!
- url: /_ah/spi/.*
  script: routes_api.APPLICATION
  secure: always

### Static
- url: /static
  static_dir: static
  secure: always

- url: .*
  script: routes.application
  secure: always

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: endpoints
  version: latest
- name: ssl
  version: latest
- name: pycrypto
  version: latest


skip_files:

- ^(.*/)?.*\py[co]
- ^(.*/)?\.DS_Store
- ^tests/.*
- ^\.git/.*