version: 0-1-0
application: huge-echo
runtime: python27
api_version: 1
threadsafe: true

includes:
- echo/include.yaml

handlers:

### Static
- url: /static
  static_dir: static
  secure: always

- url: .*
  script: routes.application
  secure: always

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

skip_files:

- ^(.*/)?.*\py[co]
- ^(.*/)?\.DS_Store
- ^tests/.*
- ^\.git/.*